### ISSUE TITLE
NextJs Bootstrap

### ISSUE THREAD

**Issue by babaskate** [contentstack/cli#1154]
When running the CLI command top bootstrap a nextjs application, the project produces an issue with running eslint. Specifically, the web vitals extension is not configured correctly in `.eslint.json`. When the adjustment is made locally, this then produces a lot of lint issues that blocks building the application.

I noticed this was fixed in the nextjs starter kit project ([master branch](https://github.com/contentstack/contentstack-nextjs-starter-app/blob/master/.eslintrc.json)), though the CLI still seems to build the project with a older revision ([cli-use](https://github.com/contentstack/contentstack-nextjs-starter-app/blob/cli-use/.eslintrc.json)). It's been difficult to track this down int the CLI source code, though see it here: https://github.com/contentstack/cli/blob/f28b829d6c60dcd81db7675f37c90620b312034f/packages/contentstack-bootstrap/src/bootstrap/github/client.ts#L10C1-L11C1

Can `cli-use` branch be updated from `master` so the latest project is installed with bootstrap?

**Comment by netrajpatel** [comment]
Hi @babaskate, 

We are working on the code merges in starter apps from `master` to `cli-use` branch and accommodating any changes required in CLI.
We will keep you posted here once this is updated.

Thank you!
