### ISSUE TITLE
Import content-types module fails

### ISSUE THREAD

**Issue by sergioviniciuss** [contentstack/cli#125]
When I run csdx import command:
`csdx cm:import -a import-token -d production-export -m content-types`

I'm getting an error saying that the content-type title already exists and therefore it won't create it and fails to proceed.

See error below:
```JSON
{
  "status": 422,
  "statusText": "Unprocessable Entity",
  "request": {
    "url": "/content_types",
    "method": "post",
    "data": "{\"content_type\":{\"title\":\"contact_information\",\"uid\":\"contact_information\",\"schema\":[{\"display_name\":\"Title\",\"uid\":\"title\",\"data_type\":\"text\",\"field_metadata\":{\"_default\":true},\"unique\":false,\"mandatory\":true,\"multiple\":false},{\"display_name\":\"URL\",\"uid\":\"url\",\"data_type\":\"text\",\"field_metadata\":{\"_default\":true},\"unique\":false,\"multiple\":false}],\"options\":{\"title\":\"title\",\"publishable\":true,\"is_page\":true,\"singleton\":false,\"sub_title\":[\"url\"],\"url_pattern\":\"/:title\",\"url_prefix\":\"/\"}}}",
    "headers": {
      "Accept": "application/json, text/plain, */*",
      "Content-Type": "application/json;charset=utf-8",
      "X-User-Agent": "contentstack-management-javascript/1.2.4",
      "User-Agent": "sdk contentstack-management-javascript/1.2.4; platform node.js/v15.4.0; os macOS/20.6.0;",
      "api_key": "bltb5839af18a3f5a96",
      "authorization": "...9309c",
      "Content-Length": 491
    }
  },
  "errorMessage": "Content Type creation failed. Please try again.",
  "errorCode": 115,
  "errors": { "title": ["is not unique."] }
}

error: The log for this is stored at production-export/logs/import
node:internal/process/promises:227
          triggerUncaughtException(err, true /* fromPromise */);
          ^

[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "undefined".] {
  code: 'ERR_UNHANDLED_REJECTION'
```

I did some investigation and found out that the import script is first importing the uid as title for the content-types. Then it's failing with this weird issue. It seems an async problem that is blocking the execution to proceed, because it first adds the content type and then tries to update it, but before that it already fails.
When I log in, I see some content types there, but they're all using their uid's as title.

Context:
The content types I'm trying to import are exported from another stack, with same configurations (master locale, languages, environments, etc). This issue is happening on csdx version: cli@0.1.1-beta.13

It works fine on cli@0.1.1-beta.3. I was trying to update the version to the latest one, but I found this blocker and decide to open this issue.

Here's an example of content-type being imported that fails: https://www.codepile.net/pile/eG7MaXmY

**Comment by netrajpatel** [comment]
Hi @sergioviniciuss,
I know it's too late to respond to your query, and I apologize for this delay.
I've tried to reproduce the same issue with the data provided by you above, but I couldn’t reproduce the same and I was able to create both global field and content types successfully with the mapping of the global field in that content type. 
It seems the reported issue has been fixed in later versions of the Contentstack CLI plugin.
I request you to please download the latest version of CLI 1.3.0 from [npm](https://www.npmjs.com/package/@contentstack/cli) and try reproducing it at your end once again.

Thanks!
