### ISSUE TITLE
Deprecation Warning when using node@21 when running import command.

### ISSUE THREAD

**Issue by alexcanessa** [contentstack/cli#1359]
When running the `csdx cm:stacks:import` command using node v21.4.0 I get a deprecation warning (which doesn't occur with v20 or lower).

While this isn't an error, the package will be deprecated soon and you might want to investigate alternative options.

```
[DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by netrajpatel** [comment]
Hi @alexcanessa,

Thanks for bringing this to our notice, we will look into the issue soon and update you.

Thank You!

**Comment by cs-raj** [comment]
Hi @alexcanessa the issue has been fixed. Please install the latest cli on node 21.
