### ISSUE TITLE
Unable to use the cli with SSO authentication

### ISSUE THREAD

**Issue by lucascaro** [contentstack/cli#454]
Hi there, after updating the CLI we're unable to use our management tokens to perform any updates, since it seems to now require email/password authentication to even add and manage tokens... Also after updating all my tokens were removed.
Why is there a requirement to log in via email / password to use the CLI? this makes it unusable for enterprise customers. Is there a plan to either add support for SSO or remove this limitation?

**Comment by shafeeqd959** [comment]
@lucascaro , We have started looking into this issue, will update you once this is fixed.

**Comment by kaelynsuh** [comment]
+1, Had the same issue as well, looks like we are able to workaround by using the previous version of the CLI in the mean time (using `@contentstack/cli@0.1.1-beta.1`)

**Comment by netrajpatel** [comment]
Hi @lucascaro, @kaelynsuh,
We have fixed these issues on the latest version of CLI 1.0.4.
Please update the package to latest version 1.0.4 and try.
For now you can add/manage tokens without login(username/password login), also we are adding OAuth support soon to enable SSO login for enterprise customers.
Thanks!
