### ISSUE TITLE
First time install - need to set correct region before login

### ISSUE THREAD

**Issue by hitolonen** [contentstack/cli#736]
Hey,

I was following https://www.contentstack.com/docs/developers/cli/install-the-cli/ and with the latest 1.5.0 while trying to login, I got error message `TypeError: Cannot read properties of undefined (reading 'cma')`.

Downgrading to 1.4.0 gave me login error `No region found, please set a region $config:set:region` and after setting that up and upgrading back to latest 1.5.0 the original error message went away.

Additionally I set my region first as EU (I'm in Europe) but login was flagged as incorrect - switching to NA region fixes the problem.

Below the commands -

Following https://www.contentstack.com/docs/developers/cli/install-the-cli/

```
% npm install -g @contentstack/cli

changed 583 packages in 4s

46 packages are looking for funding
  run `npm fund` for details
% csdx --version
@contentstack/cli/1.5.0 darwin-arm64 node-v20.0.0
% csdx auth:login 
    TypeError: Cannot read properties of undefined (reading 'cma')
```

Downgrading to 1.4.0 and getting region set msg.

```
% npm install -g @contentstack/cli@1.4.0

removed 4 packages, and changed 579 packages in 4s

46 packages are looking for funding
  run `npm fund` for details
% csdx --version 

@contentstack/cli/1.4.0 darwin-arm64 node-v20.0.0
% 
% csdx auth:login 
No region found, please set a region $config:set:region
% csdx config:set:region EU
Region has been set to EU
CDA HOST: https://eu-cdn.contentstack.com
CMA HOST: https://eu-api.contentstack.com
% csdx auth:login          

 Currently using EU region 

? Enter your email address 
```

Upgrading back to 1.5.0 and can move to login.

```
% npm install -g @contentstack/cli

added 4 packages, and changed 579 packages in 22s

46 packages are looking for funding
  run `npm fund` for details
% csdx auth:login                 
? Enter your email address 
```

Login with regions

```
csdx auth:login

 Currently using EU region 

? Enter your email address ***
? Enter your password ***
Login Error
Looks like your email or password is invalid. Please try again or reset your password.
% csdx config:set:region NA
Region has been set to NA
CDA HOST: https://cdn.contentstack.io
CMA HOST: https://api.contentstack.io
% csdx auth:login          

 Currently using NA region 

? Enter your email address ***
? Enter your password ***
Successfully logged in!!
```

Not sure if these are bugs or workflow issues, but having better error messaging for end user (eg requiring correct region before trying to login) and https://www.contentstack.com/docs/developers/cli/install-the-cli/ reflecting these would be helpful 😄

**Comment by netrajpatel** [comment]
Hi @hitolonen,
We are investigating this issue, and update you in some time.

**Comment by joechoi-git** [comment]
I ran into the same issue, but https://github.com/hitolonen's workaround helped me resolve it!

**Comment by timothyjoh** [comment]
Also saw this issue today, worked around it with the `npx csdx config:region:set NA` as well before logging in

**Comment by cs-raj** [comment]
Hi @hitolonen , Please install the latest cli. We have handled the case when region is not set and you try to login you will get the proper error.
