### ISSUE TITLE
cm:stacks:seed results in error

### ISSUE THREAD

**Issue by korve** [contentstack/cli#829]
I try to follow the starter tutorial at https://www.contentstack.com/docs/developers/sample-apps/build-a-starter-website-using-nuxt3-and-contentstack/#import-content. In step 3 it is required to import the starter content. The command `csdx cm:stacks:seed --repo "contentstack/stack-starter-app"` results in the following error:

```
Creating Stack 'nuxt_starter' within Organization '[ORG NAME]'... !
    TypeError: Cannot read properties of undefined (reading 'data')
```

No other information is given.

Here are my versions:

```
$ node --version
v20.2.0
```

```
$ csdx --version
@contentstack/cli/1.7.5 darwin-x64 node-v20.2.0
```

```
macOS Ventura 13.4
```

**Comment by netrajpatel** [comment]
Hi @korve,
Thanks for letting this in our notice, we are on it.
This error is thrown when you do not have admin or owner access to your organization. Can you ask your organization owner to give you the required permissions and try?

**Comment by korve** [comment]
Ok that did the trick. A more helpful error message would be an improvement. Thanks!
