### ISSUE TITLE
Feature Request: Support clone across regions

### ISSUE THREAD

**Issue by mikebell** [contentstack/cli#93]
We have a stack in a demo account in the US region that we'd like to move to the production stack in EU. Currently the clone command only support cloning in the same region. It would be helpful if you could set the region when cloning through the cli.

**Comment by shafeeqd959** [comment]
@mikebell , You achieve this by a two step process.Using export command, export the content on US region and switch the region to EU and use import command to import to the EU region. Will check the feasibility of adding this feature in clone command and update you. Thanks
